### PR TITLE
Preserve comments

### PR DESCRIPTION
**Pull request by bhrutledge**
First, thanks for this and setup-py-upgrade! They were very helpful in migrating from `setup.py`.

This is just a failing test for an issue I encountered (via pre-commit) while attempting to document the reasons for config lines.

### CODE REVIEW

**Comment by bhrutledge** [comment]
I should have added that I'm not in a place to fix this right now; just wanted to document it.

**Comment by asottile** [comment]
I intentionally did not try and implement this as it's hard (impossible?) without a functioning CST (or even a halfway decent AST which we don't have either!)

I found (at least for my projects and ones I have access to) that almost all of the comments were entirely superfluous or well-covered by `git blame` or other supporting evidence such that the comments were not helpful (for instance, no need to explain flake8 codes you can just google them, `max-line-length = 88` returns some pretty helpful google results given it's a very special snowflake number).

that said, I'd be happy if something like this got eventually implemented -- but I don't see the benefit in leaving an open broken PR for an extended (indefinite?) period of time -- happy to hear your thoughts though :)

**Comment by bhrutledge** [comment]
Thanks, @asottile. I'm still learning how to set up a project by some definition of "right", with a goal of using it as an example (or cookiecutter) in the future. To that end, I find comments useful. Here's an example: https://github.com/bhrutledge/pytest-quarantine/blob/master/setup.cfg

That said, I think I'm going to break out the tool config into tool-specific config files, which would avoid this issue.

No need to leave this PR open; I'll let you add an issue if you like, but otherwise I'll trust GitHub search to turn it up for folks who might be interested in the future.

**Comment by asottile** [comment]
that's fair, I actually lean the opposite direction though -- no need to duplicate documentation (poorly and prone to bitrot) in comments across all the results -- to each their own though :)

**Comment by glensc** [comment]
Pro-tip: you can use git line-based staging (`git add -p`), and not stage chunks that remove comments!

**Comment by alonbl** [comment]
Removing comments is unexpected and very bad practice.

It is important to explain why a section/statement was added and preserve the reasoning during reading/reviewing/copying/applying.

Using git history is not a solution for preserving valid authoritative documentation.

Let's stretch this and strip down comments in our programs... and dig anything using git blame to reverse engineer the intention of people, while copy the history from one project to another as we need to preserve the history of the source projects to [poorly] understand the next one.

Please reopen, comments are important to human, it is the glue between the human intelligence and the implementation.

**Pull request closed without merging**
